# Generated by Django 4.1.7 on 2023-04-11 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_likes_post_post_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_like',
            new_name='like',
        ),
    ]
