# Generated by Django 4.1.7 on 2023-04-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_post_like_post_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Comment',
            field=models.ManyToManyField(related_name='liked_posts', to='posts.comment'),
        ),
    ]
