# Generated by Django 4.1.7 on 2023-04-19 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='reponses',
            new_name='responses',
        ),
    ]
