# Generated by Django 4.1.7 on 2023-04-19 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_response_votes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='response',
            options={},
        ),
        migrations.AlterField(
            model_name='response',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='response_votes', to='forum.vote'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_votes', to='forum.response'),
        ),
    ]
