# Generated by Django 4.1.7 on 2023-04-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_alter_response_options_alter_response_votes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='votes_response', to='forum.vote'),
        ),
    ]
