# Generated by Django 4.1.7 on 2023-04-11 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='current_semester',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
