# Generated by Django 4.1.7 on 2023-04-11 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_academicinfo_current_semester'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyinfo',
            old_name='company',
            new_name='company_name',
        ),
    ]
