# Generated by Django 4.1.7 on 2023-04-11 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_company_companyinfo_company_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyinfo',
            old_name='designation',
            new_name='role',
        ),
    ]
