# Generated by Django 4.1.7 on 2023-04-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_designation_companyinfo_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='roll_number',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
